name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Azure Storage Action
      uses: lauchacarro/Azure-Storage-Action@v1.0
      with:
        # Connection String of the Azure Storage Container
        connection-string: ${{ secrets.UKS_Storage_Key }}
        # Folder what contains the files for upload to Storage Container
        folder: /webroot/*
        # Name of Blob Container Storage
        blob-container-name: $web
        # Enabled static website
        enabled-static-website: true
